// Code generated by mockery v1.0.1 DO NOT EDIT.

package mocks

import db "github.com/quilt/quilt/db"
import mock "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Client) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Deploy provides a mock function with given fields: deployment
func (_m *Client) Deploy(deployment string) error {
	ret := _m.Called(deployment)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(deployment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// QueryClusters provides a mock function with given fields:
func (_m *Client) QueryClusters() ([]db.Cluster, error) {
	ret := _m.Called()

	var r0 []db.Cluster
	if rf, ok := ret.Get(0).(func() []db.Cluster); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Cluster)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryConnections provides a mock function with given fields:
func (_m *Client) QueryConnections() ([]db.Connection, error) {
	ret := _m.Called()

	var r0 []db.Connection
	if rf, ok := ret.Get(0).(func() []db.Connection); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Connection)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryContainers provides a mock function with given fields:
func (_m *Client) QueryContainers() ([]db.Container, error) {
	ret := _m.Called()

	var r0 []db.Container
	if rf, ok := ret.Get(0).(func() []db.Container); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Container)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryEtcd provides a mock function with given fields:
func (_m *Client) QueryEtcd() ([]db.Etcd, error) {
	ret := _m.Called()

	var r0 []db.Etcd
	if rf, ok := ret.Get(0).(func() []db.Etcd); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Etcd)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryLabels provides a mock function with given fields:
func (_m *Client) QueryLabels() ([]db.Label, error) {
	ret := _m.Called()

	var r0 []db.Label
	if rf, ok := ret.Get(0).(func() []db.Label); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Label)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryMachines provides a mock function with given fields:
func (_m *Client) QueryMachines() ([]db.Machine, error) {
	ret := _m.Called()

	var r0 []db.Machine
	if rf, ok := ret.Get(0).(func() []db.Machine); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Machine)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Version provides a mock function with given fields:
func (_m *Client) Version() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
